# Generated by Django 5.1.4 on 2026-06-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecosystem', '0001_initial'),
        ('entities', '0002_alter_entities_approvalstatus_and_more'),
        ('shared', '0003_alter_auditlog_logid_alter_auditlog_retentiontier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcels',
            fields=[
                ('Status', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted')),
                ('ApprovalStatus', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending')),
                ('DeletedAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('LandParcelId', models.AutoField(primary_key=True, serialize=False)),
                ('ParcelName', models.CharField(max_length=200)),
                ('ParcelReference', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('AreaHectares', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('BoundaryGeoJSON', models.JSONField(blank=True, help_text='GeoJSON polygon boundary', null=True)),
                ('Tenure', models.CharField(blank=True, max_length=100, null=True)),
                ('LandUseType', models.CharField(blank=True, max_length=100, null=True)),
                ('PlanningReference', models.CharField(blank=True, max_length=100, null=True)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land_parcels', to='entities.entities')),
            ],
            options={
                'db_table': 'land_parcels',
            },
        ),
        migrations.CreateModel(
            name='LandParcelLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcel_locations', to='shared.locations')),
                ('LandParcelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_locations', to='land.landparcels')),
            ],
            options={
                'db_table': 'land_parcel_locations',
            },
        ),
        migrations.CreateModel(
            name='LandParcelImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ImageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcel_images', to='shared.images')),
                ('LandParcelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_images', to='land.landparcels')),
            ],
            options={
                'db_table': 'land_parcel_images',
            },
        ),
        migrations.CreateModel(
            name='LandParcelEntities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_entity_links', to='entities.entities')),
                ('LandParcelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_entities', to='land.landparcels')),
            ],
            options={
                'db_table': 'land_parcel_entities',
            },
        ),
        migrations.CreateModel(
            name='LandParcelEcosystems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EcosystemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcel_links', to='ecosystem.ecosystem')),
                ('LandParcelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_ecosystems', to='land.landparcels')),
            ],
            options={
                'db_table': 'land_parcel_ecosystems',
            },
        ),
        migrations.CreateModel(
            name='LandParcelDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DocumentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcel_documents', to='shared.documents')),
                ('LandParcelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_documents', to='land.landparcels')),
            ],
            options={
                'db_table': 'land_parcel_documents',
            },
        ),
        migrations.CreateModel(
            name='LandParcelContacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ContactId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcel_contacts', to='shared.contacts')),
                ('LandParcelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_contacts', to='land.landparcels')),
            ],
            options={
                'db_table': 'land_parcel_contacts',
            },
        ),
        migrations.CreateModel(
            name='LandParcelTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LandParcelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcel_tags', to='land.landparcels')),
                ('TagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcel_links', to='shared.tags')),
            ],
            options={
                'db_table': 'land_parcel_tags',
            },
        ),
    ]
