# Generated by Django 5.1.4 on 2026-06-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_alter_entities_approvalstatus_and_more'),
        ('land', '0001_initial'),
        ('shared', '0003_alter_auditlog_logid_alter_auditlog_retentiontier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProjects',
            fields=[
                ('Status', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted')),
                ('ApprovalStatus', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending')),
                ('DeletedAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=200)),
                ('ProjectReference', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('ProjectType', models.CharField(blank=True, max_length=100, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('TotalAreaHectares', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('EstimatedValueGBP', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='entities.entities')),
            ],
            options={
                'db_table': 'development_projects',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectPartners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PartnerSharePercent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('PartnerConsolidationApproach', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Equity Share'), (2, 'Financial Control'), (3, 'Operational Control')], null=True)),
                ('IsDoubleCountingRisk', models.BooleanField(default=False)),
                ('DoubleCountingNotes', models.TextField(blank=True, null=True)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_projects', to='entities.entities')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_partners', to='projects.developmentprojects')),
            ],
            options={
                'db_table': 'development_project_partners',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectLandParcels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LandParcelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='land.landparcels')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_land_parcels', to='projects.developmentprojects')),
            ],
            options={
                'db_table': 'development_project_land_parcels',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ImageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='shared.images')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.developmentprojects')),
            ],
            options={
                'db_table': 'development_project_images',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectEntities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_entity_links', to='entities.entities')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_entities', to='projects.developmentprojects')),
            ],
            options={
                'db_table': 'development_project_entities',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DocumentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='shared.documents')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='projects.developmentprojects')),
            ],
            options={
                'db_table': 'development_project_documents',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectContacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ContactId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contacts', to='shared.contacts')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contacts', to='projects.developmentprojects')),
            ],
            options={
                'db_table': 'development_project_contacts',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentProjectTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tags', to='projects.developmentprojects')),
                ('TagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='shared.tags')),
            ],
            options={
                'db_table': 'development_project_tags',
            },
        ),
        migrations.CreateModel(
            name='ProjectPhases',
            fields=[
                ('Status', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted')),
                ('ApprovalStatus', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending')),
                ('DeletedAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('PhaseId', models.AutoField(primary_key=True, serialize=False)),
                ('PhaseName', models.CharField(max_length=200)),
                ('PhaseNumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('TargetEmissionsTonnes', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_phases', to='entities.entities')),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.developmentprojects')),
            ],
            options={
                'db_table': 'project_phases',
            },
        ),
        migrations.CreateModel(
            name='RelatedProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RelationshipType', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('PrimaryProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_as_primary', to='projects.developmentprojects')),
                ('RelatedProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_as_secondary', to='projects.developmentprojects')),
            ],
            options={
                'db_table': 'related_projects',
            },
        ),
        migrations.AddIndex(
            model_name='developmentprojects',
            index=models.Index(fields=['EntityId', 'Status'], name='idx_project_entity_status'),
        ),
        migrations.AddIndex(
            model_name='developmentprojectpartners',
            index=models.Index(fields=['EntityId', 'ProjectId'], name='idx_project_partner_entity'),
        ),
        migrations.AddConstraint(
            model_name='relatedprojects',
            constraint=models.UniqueConstraint(fields=('PrimaryProjectId', 'RelatedProjectId'), name='unique_project_relation'),
        ),
    ]
