# Generated by Django 5.1.4 on 2026-06-22 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_alter_entities_approvalstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('NotificationId', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('user_created', 'New User Created'), ('emissions_submitted', 'Emissions Record Submitted'), ('emissions_verified', 'Emissions Record Verified'), ('emissions_unlocked', 'Verified Record Unlocked'), ('system_error', 'System Error'), ('access_denied', 'Access Denied Attempt'), ('entity_created', 'New Entity Created'), ('password_reset', 'Password Reset Requested'), ('report_ready', 'Report Generation Complete'), ('report_failed', 'Report Generation Failed')], max_length=50)),
                ('Title', models.CharField(max_length=200)),
                ('Body', models.TextField()),
                ('RelatedModule', models.CharField(blank=True, max_length=50, null=True)),
                ('RelatedRecordId', models.IntegerField(blank=True, null=True)),
                ('IsRead', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='entities.entities')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['UserId', 'IsRead', 'CreatedAt'], name='idx_notif_user_unread'), models.Index(fields=['EntityId'], name='idx_notif_entity')],
            },
        ),
    ]
