# Generated by Django 5.1.4 on 2026-06-22 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_alter_entities_approvalstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('Status', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted')),
                ('ApprovalStatus', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending')),
                ('DeletedAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('BlogId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Slug', models.SlugField(max_length=220, unique=True)),
                ('PostBody', models.TextField()),
                ('BlogStatus', models.PositiveSmallIntegerField(default=1, help_text='1: Draft, 2: Published, 3: Archived')),
                ('PublishedAt', models.DateTimeField(blank=True, null=True)),
                ('SeoTitle', models.CharField(blank=True, max_length=60, null=True)),
                ('SeoDescription', models.CharField(blank=True, max_length=160, null=True)),
                ('EmbedUrls', models.JSONField(default=list)),
                ('FeaturedImageId', models.IntegerField(blank=True, null=True)),
                ('AuthorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_posts', to=settings.AUTH_USER_MODEL)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to='entities.entities')),
            ],
            options={
                'db_table': 'blogs',
                'indexes': [models.Index(fields=['Slug'], name='idx_blog_slug'), models.Index(fields=['BlogStatus', 'PublishedAt'], name='idx_blog_status_published')],
            },
        ),
    ]
