# Generated by Django 5.1.4 on 2026-08-31 05:35

from django.db import migrations, models

# Columns that are about to become NOT NULL. Existing NULLs must become '' first,
# otherwise the AlterField operations below fail on any populated database.
NULLABLE_TEXT_COLUMNS = {
    "blogs": ["SeoDescription", "SeoTitle"],
}


def backfill_empty_strings(apps, schema_editor):
    for model_name, field_names in NULLABLE_TEXT_COLUMNS.items():
        model = apps.get_model("blog", model_name)
        for field_name in field_names:
            model._default_manager.filter(**{field_name + "__isnull": True}).update(
                **{field_name: ""}
            )


def noop(apps, schema_editor):
    """Reverse is a no-op — '' and NULL are indistinguishable once merged."""


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_options'),
    ]

    operations = [
        migrations.RunPython(backfill_empty_strings, noop),
        migrations.AlterField(
            model_name='blogs',
            name='SeoDescription',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='SeoTitle',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
