/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface BlogsDetailRequest {
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  Title: string;
  /**
   * @minLength 1
   * @maxLength 220
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  Slug: string;
  /** @minLength 1 */
  PostBody: string;
  /**
   * 1: Draft, 2: Published, 3: Archived
   * @minimum 0
   * @maximum 32767
   */
  BlogStatus?: number;
  /**
   * @maxLength 60
   * @nullable
   */
  SeoTitle?: string | null;
  /**
   * @maxLength 160
   * @nullable
   */
  SeoDescription?: string | null;
  EmbedUrls?: unknown;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  FeaturedImageId?: number | null;
  /** @nullable */
  AuthorId?: number | null;
}
