/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface BlogsList {
  readonly BlogId: number;
  /** @maxLength 200 */
  Title: string;
  /**
   * @maxLength 220
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  Slug: string;
  /**
   * 1: Draft, 2: Published, 3: Archived
   * @minimum 0
   * @maximum 32767
   */
  BlogStatus?: number;
  /** @nullable */
  PublishedAt?: string | null;
  /** @maxLength 60 */
  SeoTitle?: string;
  /** @nullable */
  AuthorId?: number | null;
  readonly CreatedAt: string;
}
