/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export type ConsolidationApproachEnum = typeof ConsolidationApproachEnum[keyof typeof ConsolidationApproachEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConsolidationApproachEnum = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
