/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export type CreditRegistryEnum = typeof CreditRegistryEnum[keyof typeof CreditRegistryEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreditRegistryEnum = {
  verra: 'verra',
  gold_standard: 'gold_standard',
  other: 'other',
} as const;
