/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectPhase } from './projectPhase';

export interface DevelopmentProjectsDetail {
  readonly ProjectId: number;
  readonly phases: readonly ProjectPhase[];
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  readonly CreatedAt: string;
  readonly UpdatedAt: string;
  /** @nullable */
  readonly CreatedBy: number | null;
  /** @nullable */
  readonly UpdatedBy: number | null;
  /** @maxLength 200 */
  ProjectName: string;
  /**
   * @maxLength 100
   * @nullable
   */
  ProjectReference?: string | null;
  /** @nullable */
  Description?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  ProjectType?: string | null;
  /** @nullable */
  StartDate?: string | null;
  /** @nullable */
  EndDate?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  Location?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  Country?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,4})?$
   */
  TotalAreaHectares?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,16}(?:\.\d{0,2})?$
   */
  EstimatedValueGBP?: string | null;
  readonly EntityId: number;
}
