/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface DevelopmentProjectsList {
  readonly ProjectId: number;
  /** @maxLength 200 */
  ProjectName: string;
  /** @maxLength 100 */
  ProjectReference?: string;
  /** @maxLength 100 */
  ProjectType?: string;
  /** @maxLength 100 */
  Country?: string;
  /** @nullable */
  StartDate?: string | null;
  /** @nullable */
  EndDate?: string | null;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  readonly phase_count: string;
}
