/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface EmissionsDataRequest {
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  Title: string;
  /**
   * @minimum 0
   * @maximum 32767
   */
  Scope: number;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  Scope3Category?: number | null;
  /** @nullable */
  ActivityDescription?: string | null;
  /** @pattern ^-?\d{0,14}(?:\.\d{0,4})?$ */
  QuantityOrCost: string;
  /**
   * @minLength 1
   * @maxLength 50
   */
  Unit: string;
  /** @pattern ^-?\d{0,10}(?:\.\d{0,8})?$ */
  EmissionFactor: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  EmissionFactorSource: string;
  /**
   * @minLength 1
   * @maxLength 50
   */
  Gas: string;
  /**
   * @maxLength 50
   * @nullable
   */
  GasSubtype?: string | null;
  /**
   * kg biogenic CO2 per canonical unit of fuel (combustion of biomass/biofuels).
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,8})?$
   */
  BiogenicCO2FactorKg?: string | null;
  /**
   * Grid-average emission factor (kg CO2e per canonical unit).
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,8})?$
   */
  EFLocationBased?: string | null;
  /**
   * Contractual/supplier emission factor (kg CO2e per canonical unit); 0 if 100% renewable EACs.
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,8})?$
   */
  EFMarketBased?: string | null;
  /**
   * @maxLength 3
   * @nullable
   */
  SpendCurrency?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,16}(?:\.\d{0,2})?$
   */
  SpendAmountLocal?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  GridSubregion?: string | null;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  BaselineYear?: number | null;
  /** @nullable */
  ReportingPeriodFrom?: string | null;
  /** @nullable */
  ReportingPeriodTo?: string | null;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  ReportingYear?: number | null;
  /**
   * @minimum 0
   * @maximum 32767
   */
  VerificationStatus?: number;
  /** @nullable */
  VerificationNotes?: string | null;
  /** @nullable */
  ProjectId?: number | null;
  /** @nullable */
  PhaseId?: number | null;
  /** @nullable */
  InventoryId?: number | null;
  /** @nullable */
  InputUnitId?: number | null;
  /** @nullable */
  EmissionFactorId?: number | null;
  GwpDatasetId: number;
}
