/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { EmissionsOffsetsRequestCreditRegistry } from './emissionsOffsetsRequestCreditRegistry';
import type { EmissionsOffsetsRequestRegistryValidationStatus } from './emissionsOffsetsRequestRegistryValidationStatus';

export interface EmissionsOffsetsRequest {
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  CreatedBy?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  UpdatedBy?: number | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  Title: string;
  /**
   * @minLength 1
   * @maxLength 100
   */
  OffsetType: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  Provider: string;
  /**
   * @maxLength 100
   * @nullable
   */
  CertificateNumber?: string | null;
  /** @pattern ^-?\d{0,12}(?:\.\d{0,6})?$ */
  OffsetAmountTonnes: string;
  /** @nullable */
  ValidFrom?: string | null;
  /** @nullable */
  ValidTo?: string | null;
  /** @nullable */
  Remarks?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  CreditSerialNumber?: string | null;
  /**
   * Which registry validates this credit (drives the registry-sync task).
   * @nullable
   */
  CreditRegistry?: EmissionsOffsetsRequestCreditRegistry;
  /** @nullable */
  RegistryValidatedAt?: string | null;
  /** @nullable */
  RegistryValidationStatus?: EmissionsOffsetsRequestRegistryValidationStatus;
  /**
   * @maxLength 300
   * @nullable
   */
  RegistryProjectName?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  RegistryProjectType?: string | null;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  RegistryVintageYear?: number | null;
  /**
   * @maxLength 300
   * @nullable
   */
  RegistryRetirementBeneficiary?: string | null;
  EmissionsId: number;
}
