/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface EmissionFactors {
  readonly FactorId: number;
  SetId: number;
  readonly set_name: string;
  readonly set_publisher: string;
  /** @maxLength 200 */
  ActivityName: string;
  /**
   * @maxLength 200
   * @nullable
   */
  ActivityCategory?: string | null;
  /**
   * @minimum 0
   * @maximum 32767
   */
  Scope: number;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  Scope3Category?: number | null;
  /** @maxLength 50 */
  Gas: string;
  /**
   * @maxLength 50
   * @nullable
   */
  GasSubtype?: string | null;
  /** @pattern ^-?\d{0,10}(?:\.\d{0,8})?$ */
  FactorValue: string;
  readonly unit: string;
  /**
   * @maxLength 3
   * @nullable
   */
  CountryCode?: string | null;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  ApplicableYear?: number | null;
}
