/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { CreditRegistryEnum } from './creditRegistryEnum';

/**
 * Which registry validates this credit (drives the registry-sync task).
 * @nullable
 */
export type EmissionsOffsetsCreditRegistry = CreditRegistryEnum | null;
