/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface EmissionFactorSets {
  readonly SetId: number;
  /** @maxLength 200 */
  SetName: string;
  /** @maxLength 200 */
  Publisher: string;
  /** @maxLength 50 */
  Version?: string;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  ApplicableYear?: number | null;
  /** @maxLength 100 */
  GeographicScope?: string;
  IsActive?: boolean;
}
