/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface EmissionsData {
  readonly EmissionsId: number;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  readonly CreatedAt: string;
  readonly UpdatedAt: string;
  /** @nullable */
  readonly CreatedBy: number | null;
  /** @nullable */
  readonly UpdatedBy: number | null;
  /** @maxLength 200 */
  Title: string;
  /**
   * @minimum 0
   * @maximum 32767
   */
  Scope: number;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  Scope3Category?: number | null;
  /** @nullable */
  ActivityDescription?: string | null;
  /** @pattern ^-?\d{0,14}(?:\.\d{0,4})?$ */
  QuantityOrCost: string;
  /** @maxLength 50 */
  Unit: string;
  /**
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,8})?$
   */
  readonly QuantityCanonical: string | null;
  /** @pattern ^-?\d{0,10}(?:\.\d{0,8})?$ */
  EmissionFactor: string;
  /** @maxLength 200 */
  EmissionFactorSource: string;
  /** @maxLength 50 */
  Gas: string;
  /**
   * @maxLength 50
   * @nullable
   */
  GasSubtype?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,14}(?:\.\d{0,4})?$
   */
  readonly EmissionsAmount: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  readonly EmissionsAmountTonnes: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,14}(?:\.\d{0,4})?$
   */
  readonly EmissionsReduced: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  readonly EmissionsReducedTonnes: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  readonly BiogenicCO2AmountTonnes: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,14}(?:\.\d{0,4})?$
   */
  readonly EmissionsAmountLocationBased: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,14}(?:\.\d{0,4})?$
   */
  readonly EmissionsAmountMarketBased: string | null;
  /**
   * @maxLength 3
   * @nullable
   */
  SpendCurrency?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,16}(?:\.\d{0,2})?$
   */
  SpendAmountLocal?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,16}(?:\.\d{0,2})?$
   */
  readonly SpendAmountUSD: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,8})?$
   */
  readonly ExchangeRateToUSD: string | null;
  /** @nullable */
  readonly ExchangeRateDate: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  GridSubregion?: string | null;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  BaselineYear?: number | null;
  /** @nullable */
  ReportingPeriodFrom?: string | null;
  /** @nullable */
  ReportingPeriodTo?: string | null;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  ReportingYear?: number | null;
  /**
   * @minimum 0
   * @maximum 32767
   */
  VerificationStatus?: number;
  /** @nullable */
  readonly VerifiedAt: string | null;
  /** @nullable */
  VerificationNotes?: string | null;
  CountsTowardNDC?: boolean;
  CountsTowardSBTi?: boolean;
  readonly EntityId: number;
  /** @nullable */
  ProjectId?: number | null;
  /** @nullable */
  PhaseId?: number | null;
  /** @nullable */
  InventoryId?: number | null;
  /** @nullable */
  InputUnitId?: number | null;
  /** @nullable */
  EmissionFactorId?: number | null;
  GwpDatasetId: number;
  /** @nullable */
  readonly VerifiedBy: number | null;
}
