/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface EmissionsDataList {
  readonly EmissionsId: number;
  /** @maxLength 200 */
  Title: string;
  /**
   * @minimum 0
   * @maximum 32767
   */
  Scope: number;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  Scope3Category?: number | null;
  /** @maxLength 50 */
  Gas: string;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  EmissionsAmountTonnes?: string | null;
  /**
   * @minimum 0
   * @maximum 32767
   */
  VerificationStatus?: number;
  /** @nullable */
  ProjectId?: number | null;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  ReportingYear?: number | null;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
}
