/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { EntityCreateEntityType } from './entityCreateEntityType';

/**
 * SA-only: creates an entity + an initial admin user.
 */
export interface EntityCreate {
  /** @maxLength 200 */
  EntityName: string;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  EntityType?: EntityCreateEntityType;
  /** @maxLength 50 */
  RegistrationNumber?: string;
  /** @maxLength 50 */
  VATNumber?: string;
  /** @maxLength 255 */
  AddressLine1?: string;
  /** @maxLength 255 */
  AddressLine2?: string;
  /** @maxLength 100 */
  City?: string;
  /** @maxLength 20 */
  PostCode?: string;
  /** @maxLength 100 */
  Country?: string;
  /** @maxLength 3 */
  BaseCurrency?: string;
  /**
   * Month number (1–12) when the entity's fiscal year ends
   * @minimum 0
   * @maximum 32767
   */
  FiscalYearEndMonth?: number;
}
