/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { EntitiesDetailRequestEntityType } from './entitiesDetailRequestEntityType';
import type { EntitiesDetailRequestConsolidationApproach } from './entitiesDetailRequestConsolidationApproach';

export interface EntitiesDetailRequest {
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  EntityName: string;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  EntityType?: EntitiesDetailRequestEntityType;
  /**
   * @maxLength 50
   * @nullable
   */
  RegistrationNumber?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  VATNumber?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  AddressLine1?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  AddressLine2?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  City?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  PostCode?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  Country?: string | null;
  /**
   * @minLength 1
   * @maxLength 3
   */
  BaseCurrency?: string;
  /**
   * Month number (1–12) when the entity's fiscal year ends
   * @minimum 0
   * @maximum 32767
   */
  FiscalYearEndMonth?: number;
  ShareEmissionsWithPartners?: boolean;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  ConsolidationApproach?: EntitiesDetailRequestConsolidationApproach;
  /**
   * @nullable
   * @pattern ^-?\d{0,3}(?:\.\d{0,3})?$
   */
  OwnershipSharePercent?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  CompaniesHouseNumber?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  SBTiCompanyId?: string | null;
  SICCodes?: unknown;
  /** @nullable */
  IncorporationDate?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  ExternalRegistryUrl?: string | null;
  /** @nullable */
  ParentEntityId?: number | null;
}
