/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { EntitiesListEntityType } from './entitiesListEntityType';

export interface EntitiesList {
  readonly EntityId: number;
  /** @maxLength 200 */
  EntityName: string;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  EntityType?: EntitiesListEntityType;
  /**
   * @maxLength 50
   * @nullable
   */
  RegistrationNumber?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  Country?: string | null;
  /** @maxLength 3 */
  BaseCurrency?: string;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  readonly CreatedAt: string;
}
