/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { EntityCreateEntityType } from './entityCreateEntityType';

/**
 * SA-only: creates an entity + an initial admin user.
 */
export interface EntityCreate {
  /** @maxLength 200 */
  EntityName: string;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  EntityType?: EntityCreateEntityType;
  /**
   * @maxLength 50
   * @nullable
   */
  RegistrationNumber?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  VATNumber?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  AddressLine1?: string | null;
  /**
   * @maxLength 255
   * @nullable
   */
  AddressLine2?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  City?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  PostCode?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  Country?: string | null;
  /** @maxLength 3 */
  BaseCurrency?: string;
  /**
   * Month number (1–12) when the entity's fiscal year ends
   * @minimum 0
   * @maximum 32767
   */
  FiscalYearEndMonth?: number;
}
