/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { GHGInventoriesRequestConsolidationApproach } from './gHGInventoriesRequestConsolidationApproach';
import type { VerificationStatusEnum } from './verificationStatusEnum';

export interface GHGInventoriesRequest {
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  CreatedBy?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  UpdatedBy?: number | null;
  /**
   * @minimum 0
   * @maximum 32767
   */
  ReportingYear: number;
  ReportingPeriodFrom: string;
  ReportingPeriodTo: string;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  BaselineYear?: number | null;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  ConsolidationApproach?: GHGInventoriesRequestConsolidationApproach;
  /**
   * @minimum 0
   * @maximum 32767
   */
  VerificationStatus?: VerificationStatusEnum;
  /** @nullable */
  VerificationNotes?: string | null;
  GwpDatasetId: number;
}
