/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { ConsolidationApproachEnum } from './consolidationApproachEnum';

/**
 * @minimum 0
 * @maximum 32767
 * @nullable
 */
export type GHGInventoriesConsolidationApproach = ConsolidationApproachEnum | null;
