/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { GHGInventoriesConsolidationApproach } from './gHGInventoriesConsolidationApproach';
import type { VerificationStatusEnum } from './verificationStatusEnum';

/**
 * Return field-specific errors for payload keys outside the API contract.
 */
export interface GHGInventories {
  readonly InventoryId: number;
  GwpDatasetId?: number;
  readonly GwpDatasetName: string;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  readonly CreatedAt: string;
  readonly UpdatedAt: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  CreatedBy?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  UpdatedBy?: number | null;
  /**
   * @minimum 0
   * @maximum 32767
   */
  ReportingYear: number;
  ReportingPeriodFrom: string;
  ReportingPeriodTo: string;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  BaselineYear?: number | null;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  ConsolidationApproach?: GHGInventoriesConsolidationApproach;
  /** Included/excluded operations and rationale for the inventory boundary. */
  BoundaryNotes?: string;
  /**
   * @minimum 0
   * @maximum 32767
   */
  VerificationStatus?: VerificationStatusEnum;
  /** @nullable */
  readonly VerifiedAt: string | null;
  VerificationNotes?: string;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  readonly TotalScope1Tonnes: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  readonly TotalScope2LocationTonnes: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  readonly TotalScope2MarketTonnes: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  readonly TotalScope3Tonnes: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  readonly TotalOffsetsTonnes: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  readonly NetEmissionsTonnes: string | null;
  /**
   * Timestamp of last scope-total recompute. NULL or >24h old => stale (see tasks.emissions).
   * @nullable
   */
  readonly TotalsLastComputedAt: string | null;
  readonly EntityId: number;
  /** @nullable */
  readonly VerifiedBy: number | null;
}
