/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { GwpValues } from './gwpValues';

export interface GwpDatasets {
  readonly GwpDatasetId: number;
  /** @maxLength 100 */
  Name: string;
  /** @maxLength 20 */
  Version: string;
  /**
   * GWP time horizon: 20 or 100
   * @minimum 0
   * @maximum 32767
   */
  Horizon: number;
  IsDefault?: boolean;
  /**
   * @minimum 0
   * @maximum 32767
   */
  PublishedYear: number;
  readonly gwp_values: readonly GwpValues[];
}
