/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface GwpValues {
  readonly GwpValueId: number;
  /** @maxLength 50 */
  Gas: string;
  /**
   * @maxLength 50
   * @nullable
   */
  GasSubtype?: string | null;
  /** @pattern ^-?\d{0,6}(?:\.\d{0,4})?$ */
  GwpFactor: string;
}
