/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export type IPCCForestTypeEnum = typeof IPCCForestTypeEnum[keyof typeof IPCCForestTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IPCCForestTypeEnum = {
  tropical: 'tropical',
  temperate: 'temperate',
  boreal: 'boreal',
  mangrove: 'mangrove',
  savanna: 'savanna',
  shrubland: 'shrubland',
  grassland: 'grassland',
} as const;
