/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export type IUCNStatusEnum = typeof IUCNStatusEnum[keyof typeof IUCNStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IUCNStatusEnum = {
  LC: 'LC',
  NT: 'NT',
  VU: 'VU',
  EN: 'EN',
  CR: 'CR',
  EW: 'EW',
  EX: 'EX',
  DD: 'DD',
  NE: 'NE',
} as const;
