/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { LandParcelsDetailBoundaryGeoJSON } from './landParcelsDetailBoundaryGeoJSON';

export interface LandParcelsDetail {
  readonly LandParcelId: number;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  readonly CreatedAt: string;
  readonly UpdatedAt: string;
  /** @nullable */
  readonly CreatedBy: number | null;
  /** @nullable */
  readonly UpdatedBy: number | null;
  /** @maxLength 200 */
  ParcelName: string;
  /**
   * @maxLength 100
   * @nullable
   */
  ParcelReference?: string | null;
  /** @nullable */
  Description?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,4})?$
   */
  AreaHectares?: string | null;
  /**
   * GeoJSON polygon boundary
   * @nullable
   */
  BoundaryGeoJSON?: LandParcelsDetailBoundaryGeoJSON;
  /**
   * @maxLength 100
   * @nullable
   */
  Tenure?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  LandUseType?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  PlanningReference?: string | null;
  readonly EntityId: number;
}
