/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface Modules {
  readonly ModuleId: number;
  /** @maxLength 100 */
  ModuleName: string;
  /** @maxLength 50 */
  ModuleKey: string;
  /** @nullable */
  Description?: string | null;
}
