/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { TypeEnum } from './typeEnum';

export interface Notifications {
  readonly NotificationId: number;
  readonly Type: TypeEnum;
  readonly Title: string;
  readonly Body: string;
  readonly RelatedModule: string;
  /** @nullable */
  readonly RelatedRecordId: number | null;
  IsRead?: boolean;
  readonly CreatedAt: string;
}
