/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { PatchedLandParcelsDetailRequestBoundaryGeoJSON } from './patchedLandParcelsDetailRequestBoundaryGeoJSON';

export interface PatchedLandParcelsDetailRequest {
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  ParcelName?: string;
  /**
   * @maxLength 100
   * @nullable
   */
  ParcelReference?: string | null;
  /** @nullable */
  Description?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,4})?$
   */
  AreaHectares?: string | null;
  /**
   * GeoJSON polygon boundary
   * @nullable
   */
  BoundaryGeoJSON?: PatchedLandParcelsDetailRequestBoundaryGeoJSON;
  /**
   * @maxLength 100
   * @nullable
   */
  Tenure?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  LandUseType?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  PlanningReference?: string | null;
}
