/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import { ConsolidationApproachEnum } from './consolidationApproachEnum';
import { NullEnum } from './nullEnum';

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchedGHGInventoriesRequestConsolidationApproach = {...ConsolidationApproachEnum,...NullEnum,} as const