/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */


/**
 * @nullable
 */
export type PatchedSpeciesDetailRequestIUCNStatus = typeof PatchedSpeciesDetailRequestIUCNStatus[keyof typeof PatchedSpeciesDetailRequestIUCNStatus]  | null;
-redeclare
export const PatchedSpeciesDetailRequestIUCNStatus = {...IUCNStatusEnum,...BlankEnum,...NullEnum,} as const