/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface ProjectPhaseRequest {
  /**
   * @minLength 1
   * @maxLength 200
   */
  PhaseName: string;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  PhaseNumber?: number | null;
  /** @nullable */
  Description?: string | null;
  /** @nullable */
  StartDate?: string | null;
  /** @nullable */
  EndDate?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,4})?$
   */
  TargetEmissionsTonnes?: string | null;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
}
