/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { ReportTypeEnum } from './reportTypeEnum';
import type { FormatEnum } from './formatEnum';
import type { JobStatusEnum } from './jobStatusEnum';

export interface ReportJob {
  readonly ReportJobId: number;
  ReportType: ReportTypeEnum;
  Format: FormatEnum;
  Parameters?: unknown;
  readonly JobStatus: JobStatusEnum;
  readonly status_label: string;
  /** @nullable */
  readonly CeleryTaskId: string | null;
  /** @nullable */
  readonly FileSizeBytes: number | null;
  /** @nullable */
  readonly ErrorMessage: string | null;
  readonly QueuedAt: string;
  /** @nullable */
  readonly StartedAt: string | null;
  /** @nullable */
  readonly CompletedAt: string | null;
  readonly PurgeAfter: string;
}
