/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface RestorationsList {
  readonly RestorationId: number;
  /** @maxLength 200 */
  RestorationName: string;
  /**
   * @maxLength 100
   * @nullable
   */
  RestorationReference?: string | null;
  /** @nullable */
  StartDate?: string | null;
  /**
   * @minimum 0
   * @maximum 2147483647
   * @nullable
   */
  TotalTreesPlanted?: number | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,4})?$
   */
  TotalAreaHectares?: string | null;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
}
