/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface RestorationsDetailRequest {
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  RestorationName: string;
  /** @maxLength 100 */
  RestorationReference?: string;
  Description?: string;
  /** @nullable */
  StartDate?: string | null;
  /** @nullable */
  CompletionDate?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,4})?$
   */
  TotalAreaHectares?: string | null;
  /**
   * @minimum 0
   * @maximum 2147483647
   * @nullable
   */
  TotalTreesPlanted?: number | null;
  MonitoringNotes?: string;
}
