/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export type RoleKeyEnum = typeof RoleKeyEnum[keyof typeof RoleKeyEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoleKeyEnum = {
  super_admin: 'super_admin',
  admin: 'admin',
  manager: 'manager',
  staff: 'staff',
} as const;
