/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { SpeciesDetailIUCNStatus } from './speciesDetailIUCNStatus';

export interface SpeciesDetail {
  readonly SpeciesId: number;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  readonly CreatedAt: string;
  readonly UpdatedAt: string;
  /** @nullable */
  readonly CreatedBy: number | null;
  /** @nullable */
  readonly UpdatedBy: number | null;
  /** FK to entities.Entities */
  readonly EntityId: number;
  /** @maxLength 200 */
  CommonName: string;
  /**
   * @maxLength 200
   * @nullable
   */
  ScientificName?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  Family?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  Kingdom?: string | null;
  /** @nullable */
  Description?: string | null;
  /** @nullable */
  IUCNStatus?: SpeciesDetailIUCNStatus;
  /** @nullable */
  readonly IUCNSyncedAt: string | null;
  /**
   * @minimum 0
   * @maximum 2147483647
   * @nullable
   */
  GBIFKey?: number | null;
}
