/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { SpeciesDetailIUCNStatus } from './speciesDetailIUCNStatus';
import type { SpeciesDetailIPCCForestType } from './speciesDetailIPCCForestType';

export interface SpeciesDetail {
  readonly SpeciesId: number;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  readonly CreatedAt: string;
  readonly UpdatedAt: string;
  /** @nullable */
  readonly CreatedBy: number | null;
  /** @nullable */
  readonly UpdatedBy: number | null;
  /** FK to entities.Entities */
  readonly EntityId: number;
  /** @maxLength 200 */
  CommonName: string;
  /**
   * @maxLength 200
   * @nullable
   */
  ScientificName?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  Family?: string | null;
  /**
   * @maxLength 50
   * @nullable
   */
  Kingdom?: string | null;
  /** @nullable */
  Description?: string | null;
  /** @nullable */
  IUCNStatus?: SpeciesDetailIUCNStatus;
  /** @nullable */
  readonly IUCNSyncedAt: string | null;
  /**
   * @minimum 0
   * @maximum 2147483647
   * @nullable
   */
  GBIFKey?: number | null;
  /**
   * IPCC forest type for Tier 1 BEF/R lookup
   * @nullable
   */
  IPCCForestType?: SpeciesDetailIPCCForestType;
  /**
   * D ΓÇö tonnes dry matter per m┬│ fresh volume (IPCC Table 4.13)
   * @nullable
   * @pattern ^-?\d{0,4}(?:\.\d{0,4})?$
   */
  BasicWoodDensity?: string | null;
  /**
   * BEF ΓÇö merchantable volume ΓåÆ total AGB (IPCC Table 4.5)
   * @nullable
   * @pattern ^-?\d{0,4}(?:\.\d{0,4})?$
   */
  BiomassExpansionFactor?: string | null;
  /**
   * R ΓÇö below-ground/above-ground biomass ratio (IPCC Table 4.4)
   * @nullable
   * @pattern ^-?\d{0,4}(?:\.\d{0,4})?$
   */
  RootToShootRatio?: string | null;
  /**
   * CF ΓÇö carbon content of dry biomass (IPCC default 0.47)
   * @nullable
   * @pattern ^-?\d{0,2}(?:\.\d{0,4})?$
   */
  CarbonFraction?: string | null;
  /**
   * Mean annual CO2e sequestered per ha at maturity (IPCC Annex 3A.1)
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,4})?$
   */
  AnnualSequestrationRateTonnesCO2ePerHa?: string | null;
  /**
   * Citation for biomass parameter values (IPCC table ref, study DOI)
   * @maxLength 200
   * @nullable
   */
  BiomassDataSource?: string | null;
}
