/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { IPCCForestTypeEnum } from './iPCCForestTypeEnum';

/**
 * IPCC forest type for Tier 1 BEF/R lookup
 * @nullable
 */
export type SpeciesDetailIPCCForestType = IPCCForestTypeEnum | null;
