/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */
import type { SpeciesListIUCNStatus } from './speciesListIUCNStatus';

export interface SpeciesList {
  readonly SpeciesId: number;
  /** @maxLength 200 */
  CommonName: string;
  /**
   * @maxLength 200
   * @nullable
   */
  ScientificName?: string | null;
  /** @nullable */
  IUCNStatus?: SpeciesListIUCNStatus;
  /**
   * @maxLength 100
   * @nullable
   */
  Family?: string | null;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
}
