/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface TargetsRequest {
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  CreatedBy?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  UpdatedBy?: number | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  TargetName: string;
  /**
   * @minLength 1
   * @maxLength 50
   */
  TargetType: string;
  /**
   * @minimum 0
   * @maximum 32767
   */
  BaselineYear: number;
  /**
   * @minimum 0
   * @maximum 32767
   */
  TargetYear: number;
  /**
   * @nullable
   * @pattern ^-?\d{0,12}(?:\.\d{0,6})?$
   */
  BaselineEmissionsTonnes?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,4}(?:\.\d{0,2})?$
   */
  ReductionPercent?: string | null;
  /**
   * @minimum 0
   * @maximum 32767
   * @nullable
   */
  Scope?: number | null;
  /**
   * @maxLength 50
   * @nullable
   */
  SBTiStatus?: string | null;
  /**
   * @minimum 0
   * @maximum 32767
   */
  ValidationStatus?: number;
  /** @nullable */
  Notes?: string | null;
}
