/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Restrict related-object inputs to the request's active entity.

Tenant-scoping a viewset's top-level queryset does not protect writes: DRF
related fields otherwise resolve primary keys from their model's global
queryset. Serializers opt in with ``tenant_owned_relationships`` mapping
input field names to the related model's entity lookup.

Input validation fails closed when the active entity context is missing.
This is intentional: silently accepting an unscoped relationship is a
tenant-isolation defect, not a recoverable serializer condition.
 */
export interface TreeRemovalsDetail {
  readonly TreeRemovalId: number;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
  /**
   * 1: Active, 2: Rejected, 3: Pending
   * @minimum 0
   * @maximum 32767
   */
  ApprovalStatus?: number;
  /** @nullable */
  DeletedAt?: string | null;
  readonly CreatedAt: string;
  readonly UpdatedAt: string;
  /** @nullable */
  readonly CreatedBy: number | null;
  /** @nullable */
  readonly UpdatedBy: number | null;
  /**
   * @maxLength 100
   * @nullable
   */
  RemovalReference?: string | null;
  /** @nullable */
  Description?: string | null;
  /** @nullable */
  RemovalDate?: string | null;
  /**
   * @minimum 0
   * @maximum 2147483647
   * @nullable
   */
  TotalTreesRemoved?: number | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,10}(?:\.\d{0,4})?$
   */
  readonly TotalBiomassCarbon: string | null;
  HasMitigationPlan?: boolean;
  /** @nullable */
  MitigationNotes?: string | null;
  readonly EntityId: number;
  /** @nullable */
  ProjectId?: number | null;
}
