/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TypeEnum = {
  user_created: 'user_created',
  emissions_submitted: 'emissions_submitted',
  emissions_verified: 'emissions_verified',
  emissions_unlocked: 'emissions_unlocked',
  system_error: 'system_error',
  access_denied: 'access_denied',
  entity_created: 'entity_created',
  password_reset: 'password_reset',
  report_ready: 'report_ready',
  report_failed: 'report_failed',
} as const;
