/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface UsersDetailRequest {
  /**
   * @minLength 1
   * @maxLength 150
   */
  username: string;
  /** @maxLength 100 */
  FirstName?: string;
  /** @maxLength 100 */
  LastName?: string;
  /** @maxLength 200 */
  Designation?: string;
  Bio?: string;
  /** @maxLength 20 */
  PhoneNumber?: string;
  /** @maxLength 500 */
  ProfilePicturePath?: string;
  is_active?: boolean;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
}
