/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, SBTi, CDP, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface UsersDetailRequest {
  /**
   * @minLength 1
   * @maxLength 150
   */
  username: string;
  /**
   * @maxLength 100
   * @nullable
   */
  FirstName?: string | null;
  /**
   * @maxLength 100
   * @nullable
   */
  LastName?: string | null;
  /**
   * @maxLength 200
   * @nullable
   */
  Designation?: string | null;
  /** @nullable */
  Bio?: string | null;
  /**
   * @maxLength 20
   * @nullable
   */
  PhoneNumber?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  ProfilePicturePath?: string | null;
  is_active?: boolean;
  /**
   * 1: Active, 2: Disabled, 3: Draft, 4: Deleted
   * @minimum 0
   * @maximum 32767
   */
  Status?: number;
}
