/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * SusDevOS API
 * GHG reporting, ecosystem tracking, and sustainable development platform. Aligned to GHG Protocol, IPCC, and TNFD.
 * OpenAPI spec version: 1.0.0
 */

export interface UserCreateRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  email: string;
  /**
   * @minLength 1
   * @maxLength 150
   */
  username: string;
  /** @maxLength 100 */
  FirstName?: string;
  /** @maxLength 100 */
  LastName?: string;
  /** @maxLength 200 */
  Designation?: string;
  /** @minLength 1 */
  role_key: string;
}
