import uuid
import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = [
        ("entities", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("UserId", models.AutoField(primary_key=True)),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(null=True, blank=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False)),
                ("EntityId", models.ForeignKey(
                    to="entities.Entities", on_delete=models.SET_NULL,
                    null=True, blank=True, related_name="users", db_column="EntityId",
                )),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("FirstName", models.CharField(max_length=100, blank=True, null=True)),
                ("LastName", models.CharField(max_length=100, blank=True, null=True)),
                ("Designation", models.CharField(max_length=200, blank=True, null=True)),
                ("Bio", models.TextField(blank=True, null=True)),
                ("ProfilePicturePath", models.CharField(max_length=500, blank=True, null=True)),
                ("PhoneNumber", models.CharField(max_length=20, blank=True, null=True)),
                ("IsSuperAdmin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("Status", models.PositiveSmallIntegerField(default=1)),
                ("ApprovalStatus", models.PositiveSmallIntegerField(default=1)),
                ("DeletedAt", models.DateTimeField(null=True, blank=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                ("CreatedBy", models.IntegerField(null=True, blank=True)),
                ("UpdatedBy", models.IntegerField(null=True, blank=True)),
                ("groups", models.ManyToManyField(
                    blank=True, related_name="users_set",
                    to="auth.Group", verbose_name="groups",
                )),
                ("user_permissions", models.ManyToManyField(
                    blank=True, related_name="users_set",
                    to="auth.Permission", verbose_name="user permissions",
                )),
            ],
            options={"db_table": "users"},
            managers=[("objects", django.contrib.auth.models.UserManager())],
        ),
        migrations.CreateModel(
            name="Modules",
            fields=[
                ("ModuleId", models.AutoField(primary_key=True)),
                ("ModuleName", models.CharField(max_length=100)),
                ("ModuleKey", models.CharField(max_length=50, unique=True)),
                ("Description", models.TextField(blank=True, null=True)),
                ("Status", models.PositiveSmallIntegerField(default=1)),
                ("ApprovalStatus", models.PositiveSmallIntegerField(default=1)),
                ("DeletedAt", models.DateTimeField(null=True, blank=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                ("CreatedBy", models.IntegerField(null=True, blank=True)),
                ("UpdatedBy", models.IntegerField(null=True, blank=True)),
            ],
            options={"db_table": "modules"},
        ),
        migrations.CreateModel(
            name="Interfaces",
            fields=[
                ("InterfaceId", models.AutoField(primary_key=True)),
                ("ModuleId", models.ForeignKey("users.Modules", on_delete=models.CASCADE, related_name="interfaces")),
                ("InterfaceName", models.CharField(max_length=100)),
                ("InterfaceKey", models.CharField(max_length=50, unique=True)),
                ("Description", models.TextField(blank=True, null=True)),
                ("Status", models.PositiveSmallIntegerField(default=1)),
                ("ApprovalStatus", models.PositiveSmallIntegerField(default=1)),
                ("DeletedAt", models.DateTimeField(null=True, blank=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                ("CreatedBy", models.IntegerField(null=True, blank=True)),
                ("UpdatedBy", models.IntegerField(null=True, blank=True)),
            ],
            options={"db_table": "interfaces"},
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("RoleId", models.AutoField(primary_key=True)),
                ("RoleName", models.CharField(max_length=100)),
                ("RoleKey", models.CharField(max_length=20, unique=True)),
                ("Description", models.TextField(blank=True, null=True)),
                ("Status", models.PositiveSmallIntegerField(default=1)),
                ("ApprovalStatus", models.PositiveSmallIntegerField(default=1)),
                ("DeletedAt", models.DateTimeField(null=True, blank=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                ("CreatedBy", models.IntegerField(null=True, blank=True)),
                ("UpdatedBy", models.IntegerField(null=True, blank=True)),
            ],
            options={"db_table": "roles"},
        ),
        migrations.CreateModel(
            name="RolePrivileges",
            fields=[
                ("RolePrivilegeId", models.AutoField(primary_key=True)),
                ("RoleId", models.ForeignKey("users.Roles", on_delete=models.CASCADE, related_name="role_privileges")),
                ("ModuleId", models.ForeignKey("users.Modules", on_delete=models.CASCADE, related_name="role_privileges")),
                ("InterfaceId", models.ForeignKey("users.Interfaces", on_delete=models.CASCADE, null=True, blank=True, related_name="role_privileges")),
                ("PermissionType", models.PositiveSmallIntegerField()),
                ("Status", models.PositiveSmallIntegerField(default=1)),
                ("ApprovalStatus", models.PositiveSmallIntegerField(default=1)),
                ("DeletedAt", models.DateTimeField(null=True, blank=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                ("CreatedBy", models.IntegerField(null=True, blank=True)),
                ("UpdatedBy", models.IntegerField(null=True, blank=True)),
            ],
            options={"db_table": "role_privileges"},
        ),
        migrations.CreateModel(
            name="UserRoles",
            fields=[
                ("UserRoleId", models.AutoField(primary_key=True)),
                ("UserId", models.ForeignKey("users.Users", on_delete=models.CASCADE, related_name="user_roles")),
                ("RoleId", models.ForeignKey("users.Roles", on_delete=models.CASCADE, related_name="user_roles")),
                ("AssignedAt", models.DateTimeField(auto_now_add=True)),
                ("Status", models.PositiveSmallIntegerField(default=1)),
                ("ApprovalStatus", models.PositiveSmallIntegerField(default=1)),
                ("DeletedAt", models.DateTimeField(null=True, blank=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                ("CreatedBy", models.IntegerField(null=True, blank=True)),
                ("UpdatedBy", models.IntegerField(null=True, blank=True)),
            ],
            options={"db_table": "user_roles"},
        ),
        migrations.CreateModel(
            name="UserPrivilegeOverrides",
            fields=[
                ("OverrideId", models.AutoField(primary_key=True)),
                ("UserId", models.ForeignKey("users.Users", on_delete=models.CASCADE, related_name="privilege_overrides")),
                ("InterfaceId", models.ForeignKey("users.Interfaces", on_delete=models.CASCADE, related_name="privilege_overrides")),
                ("PermissionType", models.PositiveSmallIntegerField()),
                ("OverrideAction", models.PositiveSmallIntegerField()),
                ("Status", models.PositiveSmallIntegerField(default=1)),
                ("ApprovalStatus", models.PositiveSmallIntegerField(default=1)),
                ("DeletedAt", models.DateTimeField(null=True, blank=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                ("CreatedBy", models.IntegerField(null=True, blank=True)),
                ("UpdatedBy", models.IntegerField(null=True, blank=True)),
            ],
            options={"db_table": "user_privilege_overrides"},
        ),
        migrations.CreateModel(
            name="DataAccessPrivileges",
            fields=[
                ("DataAccessPrivilegeId", models.AutoField(primary_key=True)),
                ("UserId", models.ForeignKey("users.Users", on_delete=models.CASCADE, related_name="data_access_privileges")),
                ("TargetEntityId", models.ForeignKey("entities.Entities", on_delete=models.CASCADE, related_name="data_access_privileges")),
                ("ModuleId", models.ForeignKey("users.Modules", on_delete=models.CASCADE, related_name="data_access_privileges")),
                ("PermissionType", models.PositiveSmallIntegerField(default=2)),
                ("Scope", models.PositiveSmallIntegerField(default=1)),
                ("RecordId", models.IntegerField(null=True, blank=True)),
                ("Status", models.PositiveSmallIntegerField(default=1)),
                ("ApprovalStatus", models.PositiveSmallIntegerField(default=1)),
                ("DeletedAt", models.DateTimeField(null=True, blank=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                ("CreatedBy", models.IntegerField(null=True, blank=True)),
                ("UpdatedBy", models.IntegerField(null=True, blank=True)),
            ],
            options={"db_table": "data_access_privileges"},
        ),
        migrations.CreateModel(
            name="PasswordResetTokens",
            fields=[
                ("TokenId", models.AutoField(primary_key=True)),
                ("UserId", models.ForeignKey("users.Users", on_delete=models.CASCADE, related_name="password_reset_tokens")),
                ("Token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("ExpiresAt", models.DateTimeField()),
                ("UsedAt", models.DateTimeField(null=True, blank=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "password_reset_tokens"},
        ),
        migrations.CreateModel(
            name="RevokedTokens",
            fields=[
                ("RevokedTokenId", models.AutoField(primary_key=True)),
                ("Jti", models.UUIDField(unique=True)),
                ("UserId", models.ForeignKey("users.Users", on_delete=models.CASCADE, related_name="revoked_tokens")),
                ("RevokedAt", models.DateTimeField(auto_now_add=True)),
                ("ExpiresAt", models.DateTimeField()),
            ],
            options={"db_table": "revoked_tokens"},
        ),
        migrations.AddIndex(
            model_name="RevokedTokens",
            index=models.Index(fields=["Jti"], name="idx_revoked_token_jti"),
        ),
    ]
