# Generated by Django 5.1.4 on 2026-06-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='dataaccessprivileges',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='dataaccessprivileges',
            name='DataAccessPrivilegeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataaccessprivileges',
            name='RecordId',
            field=models.IntegerField(blank=True, help_text='NULL = all records in module', null=True),
        ),
        migrations.AlterField(
            model_name='dataaccessprivileges',
            name='Scope',
            field=models.PositiveSmallIntegerField(default=1, help_text='1=SameHierarchy, 2=CrossHierarchy'),
        ),
        migrations.AlterField(
            model_name='dataaccessprivileges',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='InterfaceId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='ModuleId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modules',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='passwordresettokens',
            name='TokenId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='revokedtokens',
            name='ExpiresAt',
            field=models.DateTimeField(help_text='When the original token would have expired'),
        ),
        migrations.AlterField(
            model_name='revokedtokens',
            name='Jti',
            field=models.UUIDField(help_text="JWT 'jti' claim — unique token identifier", unique=True),
        ),
        migrations.AlterField(
            model_name='revokedtokens',
            name='RevokedTokenId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roleprivileges',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='roleprivileges',
            name='InterfaceId',
            field=models.ForeignKey(blank=True, help_text='NULL = applies to all interfaces in the module', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_privileges', to='users.interfaces'),
        ),
        migrations.AlterField(
            model_name='roleprivileges',
            name='PermissionType',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Create'), (2, 'Read'), (3, 'Update'), (4, 'Delete'), (5, 'All')]),
        ),
        migrations.AlterField(
            model_name='roleprivileges',
            name='RolePrivilegeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roleprivileges',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='RoleId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='RoleKey',
            field=models.CharField(choices=[('super_admin', 'SuperAdmin'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='userprivilegeoverrides',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='userprivilegeoverrides',
            name='OverrideAction',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Grant'), (2, 'Revoke')]),
        ),
        migrations.AlterField(
            model_name='userprivilegeoverrides',
            name='OverrideId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprivilegeoverrides',
            name='PermissionType',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Create'), (2, 'Read'), (3, 'Update'), (4, 'Delete'), (5, 'All')]),
        ),
        migrations.AlterField(
            model_name='userprivilegeoverrides',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='UserRoleId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='users',
            name='UserId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
