# Generated by Django 5.1.4 on 2026-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfaces',
            options={'ordering': ['InterfaceKey']},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={'ordering': ['ModuleKey']},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'ordering': ['RoleName']},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['email']},
        ),
        migrations.AlterField(
            model_name='revokedtokens',
            name='Jti',
            field=models.UUIDField(help_text="JWT 'jti' claim -- unique token identifier", unique=True),
        ),
    ]
