# Generated by Django 5.1.4 on 2026-06-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_alter_entities_approvalstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('PlanId', models.AutoField(primary_key=True, serialize=False)),
                ('PlanKey', models.CharField(max_length=50, unique=True)),
                ('PlanName', models.CharField(max_length=100)),
                ('PriceMonthlyGBP', models.PositiveIntegerField()),
                ('PriceAnnualGBP', models.PositiveIntegerField()),
                ('MaxEntities', models.PositiveSmallIntegerField(help_text='0 = unlimited')),
                ('MaxUsersPerEntity', models.PositiveSmallIntegerField(help_text='0 = unlimited')),
                ('MaxReportingYears', models.PositiveSmallIntegerField(help_text='0 = unlimited; 1 = current year only')),
                ('MaxApiCallsPerDay', models.PositiveIntegerField(default=0, help_text='0 = no API access')),
                ('AdditionalEntityPriceGBP', models.PositiveIntegerField(default=0)),
                ('SupportTier', models.CharField(max_length=50)),
                ('IsPublic', models.BooleanField(default=True)),
                ('SortOrder', models.PositiveSmallIntegerField(default=0)),
                ('StripePriceIdMonthly', models.CharField(blank=True, max_length=100, null=True)),
                ('StripePriceIdAnnual', models.CharField(blank=True, max_length=100, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='PlanFeatures',
            fields=[
                ('PlanFeatureId', models.AutoField(primary_key=True, serialize=False)),
                ('FeatureKey', models.CharField(max_length=100)),
                ('IsEnabled', models.BooleanField(default=True)),
                ('LimitValue', models.PositiveIntegerField(blank=True, null=True)),
                ('UpgradeMessage', models.TextField()),
                ('PlanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='billing.plans')),
            ],
            options={
                'db_table': 'plan_features',
                'indexes': [models.Index(fields=['PlanId', 'FeatureKey'], name='idx_plan_feature_key')],
                'constraints': [models.UniqueConstraint(fields=('PlanId', 'FeatureKey'), name='unique_feature_per_plan')],
            },
        ),
        migrations.CreateModel(
            name='EntitySubscriptions',
            fields=[
                ('SubscriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trial'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='active', max_length=20)),
                ('BillingInterval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('TrialEndsAt', models.DateTimeField(blank=True, null=True)),
                ('CurrentPeriodStart', models.DateTimeField(blank=True, null=True)),
                ('CurrentPeriodEnd', models.DateTimeField(blank=True, null=True)),
                ('CanceledAt', models.DateTimeField(blank=True, null=True)),
                ('CancelAtPeriodEnd', models.BooleanField(default=False)),
                ('StripeCustomerId', models.CharField(blank=True, max_length=100, null=True)),
                ('StripeSubscriptionId', models.CharField(blank=True, max_length=100, null=True)),
                ('StripeLatestInvoiceId', models.CharField(blank=True, max_length=100, null=True)),
                ('AdditionalEntities', models.PositiveSmallIntegerField(default=0)),
                ('DiscountCode', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('EntityId', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='entities.entities')),
                ('PlanId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plans')),
            ],
            options={
                'db_table': 'entity_subscriptions',
                'indexes': [models.Index(fields=['StripeCustomerId'], name='idx_sub_stripe_customer'), models.Index(fields=['StripeSubscriptionId'], name='idx_sub_stripe_subscription')],
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('UsageId', models.AutoField(primary_key=True, serialize=False)),
                ('PeriodStart', models.DateField()),
                ('PeriodEnd', models.DateField()),
                ('ActiveUsersCount', models.PositiveSmallIntegerField(default=0)),
                ('ReportingYearsCount', models.PositiveSmallIntegerField(default=0)),
                ('ApiCallsToday', models.PositiveIntegerField(default=0)),
                ('ApiCallsMonth', models.PositiveIntegerField(default=0)),
                ('TotalEmissionsRecords', models.PositiveIntegerField(default=0)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to='entities.entities')),
            ],
            options={
                'db_table': 'usage_tracking',
                'constraints': [models.UniqueConstraint(fields=('EntityId', 'PeriodStart'), name='unique_usage_per_entity_period')],
            },
        ),
    ]
