# Generated by Django 5.1.4 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_entitysubscriptions_discountcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundingPartnerApplication",
            fields=[
                ("ApplicationId", models.AutoField(primary_key=True, serialize=False)),
                ("FullName", models.CharField(max_length=150)),
                ("Email", models.EmailField(db_index=True, max_length=254)),
                ("CompanyName", models.CharField(max_length=200)),
                ("Role", models.CharField(max_length=150)),
                ("Website", models.URLField(blank=True)),
                ("UseCase", models.CharField(max_length=100)),
                ("LiveProject", models.TextField()),
                ("ExpectedUsers", models.PositiveSmallIntegerField()),
                ("CurrentTooling", models.CharField(blank=True, max_length=200)),
                ("Message", models.TextField(blank=True)),
                ("ConsentToFollowUp", models.BooleanField(default=False)),
                ("Status", models.CharField(choices=[("new", "New"), ("reviewing", "Reviewing"), ("accepted", "Accepted"), ("declined", "Declined")], db_index=True, default="new", max_length=20)),
                ("InternalNotes", models.TextField(blank=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "founding_partner_applications",
                "ordering": ["-CreatedAt"],
            },
        ),
    ]
