# Generated by Django 5.1.4 on 2026-06-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecosystem', '0001_initial'),
        ('entities', '0002_alter_entities_approvalstatus_and_more'),
        ('land', '0001_initial'),
        ('projects', '0001_initial'),
        ('shared', '0003_alter_auditlog_logid_alter_auditlog_retentiontier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restorations',
            fields=[
                ('Status', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted')),
                ('ApprovalStatus', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending')),
                ('DeletedAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('RestorationId', models.AutoField(primary_key=True, serialize=False)),
                ('RestorationName', models.CharField(max_length=200)),
                ('RestorationReference', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('CompletionDate', models.DateField(blank=True, null=True)),
                ('TotalAreaHectares', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('TotalTreesPlanted', models.PositiveIntegerField(blank=True, null=True)),
                ('EstimatedCarbonSequestrationTonnes', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('MonitoringNotes', models.TextField(blank=True, null=True)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restorations', to='entities.entities')),
            ],
            options={
                'db_table': 'restorations',
            },
        ),
        migrations.CreateModel(
            name='RestorationLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_links', to='shared.locations')),
                ('RestorationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_locations', to='restorations.restorations')),
            ],
            options={
                'db_table': 'restoration_locations',
            },
        ),
        migrations.CreateModel(
            name='RestorationLandParcels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LandParcelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_links', to='land.landparcels')),
                ('RestorationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_land_parcels', to='restorations.restorations')),
            ],
            options={
                'db_table': 'restoration_land_parcels',
            },
        ),
        migrations.CreateModel(
            name='RestorationImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ImageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_images', to='shared.images')),
                ('RestorationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_images', to='restorations.restorations')),
            ],
            options={
                'db_table': 'restoration_images',
            },
        ),
        migrations.CreateModel(
            name='RestorationEntities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_entity_links', to='entities.entities')),
                ('RestorationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_entities', to='restorations.restorations')),
            ],
            options={
                'db_table': 'restoration_entities',
            },
        ),
        migrations.CreateModel(
            name='RestorationEcosystems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EcosystemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_links', to='ecosystem.ecosystem')),
                ('RestorationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_ecosystems', to='restorations.restorations')),
            ],
            options={
                'db_table': 'restoration_ecosystems',
            },
        ),
        migrations.CreateModel(
            name='RestorationDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DocumentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_documents', to='shared.documents')),
                ('RestorationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_documents', to='restorations.restorations')),
            ],
            options={
                'db_table': 'restoration_documents',
            },
        ),
        migrations.CreateModel(
            name='RestorationDevelopmentProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_links', to='projects.developmentprojects')),
                ('RestorationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_projects', to='restorations.restorations')),
            ],
            options={
                'db_table': 'restoration_development_projects',
            },
        ),
        migrations.CreateModel(
            name='RestorationContacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ContactId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_contacts', to='shared.contacts')),
                ('RestorationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_contacts', to='restorations.restorations')),
            ],
            options={
                'db_table': 'restoration_contacts',
            },
        ),
        migrations.CreateModel(
            name='RestorationSpecies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Count', models.PositiveIntegerField(blank=True, null=True)),
                ('RestorationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_species', to='restorations.restorations')),
                ('SpeciesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_links', to='ecosystem.species')),
            ],
            options={
                'db_table': 'restoration_species',
            },
        ),
        migrations.CreateModel(
            name='RestorationTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RestorationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_tags', to='restorations.restorations')),
                ('TagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoration_links', to='shared.tags')),
            ],
            options={
                'db_table': 'restoration_tags',
            },
        ),
        migrations.CreateModel(
            name='TreeRemovals',
            fields=[
                ('Status', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted')),
                ('ApprovalStatus', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending')),
                ('DeletedAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('TreeRemovalId', models.AutoField(primary_key=True, serialize=False)),
                ('RemovalReference', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('RemovalDate', models.DateField(blank=True, null=True)),
                ('TotalTreesRemoved', models.PositiveIntegerField(blank=True, null=True)),
                ('TotalBiomassCarbon', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('HasMitigationPlan', models.BooleanField(default=False)),
                ('MitigationNotes', models.TextField(blank=True, null=True)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tree_removals', to='entities.entities')),
                ('ProjectId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_removals', to='projects.developmentprojects')),
            ],
            options={
                'db_table': 'tree_removals',
            },
        ),
        migrations.CreateModel(
            name='TreeRemovalRemovedSpecies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Count', models.PositiveIntegerField(blank=True, null=True)),
                ('SpeciesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_removal_removals', to='ecosystem.species')),
                ('TreeRemovalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_species', to='restorations.treeremovals')),
            ],
            options={
                'db_table': 'tree_removal_removed_species',
            },
        ),
        migrations.CreateModel(
            name='TreeRemovalLandParcels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LandParcelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_removal_links', to='land.landparcels')),
                ('TreeRemovalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_land_parcels', to='restorations.treeremovals')),
            ],
            options={
                'db_table': 'tree_removal_land_parcels',
            },
        ),
        migrations.CreateModel(
            name='TreeRemovalImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ImageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_removal_images', to='shared.images')),
                ('TreeRemovalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_images', to='restorations.treeremovals')),
            ],
            options={
                'db_table': 'tree_removal_images',
            },
        ),
        migrations.CreateModel(
            name='TreeRemovalEntities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_removal_entity_links', to='entities.entities')),
                ('TreeRemovalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_entities', to='restorations.treeremovals')),
            ],
            options={
                'db_table': 'tree_removal_entities',
            },
        ),
        migrations.CreateModel(
            name='TreeRemovalEcosystems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EcosystemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_removal_links', to='ecosystem.ecosystem')),
                ('TreeRemovalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_ecosystems', to='restorations.treeremovals')),
            ],
            options={
                'db_table': 'tree_removal_ecosystems',
            },
        ),
        migrations.CreateModel(
            name='TreeRemovalDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DocumentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_removal_documents', to='shared.documents')),
                ('TreeRemovalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_documents', to='restorations.treeremovals')),
            ],
            options={
                'db_table': 'tree_removal_documents',
            },
        ),
        migrations.CreateModel(
            name='TreeRemovalContacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ContactId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_removal_contacts', to='shared.contacts')),
                ('TreeRemovalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_contacts', to='restorations.treeremovals')),
            ],
            options={
                'db_table': 'tree_removal_contacts',
            },
        ),
        migrations.CreateModel(
            name='TreeRemovalAffectedSpecies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('SpeciesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_removal_affected', to='ecosystem.species')),
                ('TreeRemovalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_species', to='restorations.treeremovals')),
            ],
            options={
                'db_table': 'tree_removal_affected_species',
            },
        ),
        migrations.CreateModel(
            name='TreeRemovalTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_removal_links', to='shared.tags')),
                ('TreeRemovalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_tags', to='restorations.treeremovals')),
            ],
            options={
                'db_table': 'tree_removal_tags',
            },
        ),
    ]
