# Generated by Django 5.1.4 on 2026-06-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0003_alter_auditlog_logid_alter_auditlog_retentiontier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('Status', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted')),
                ('ApprovalStatus', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending')),
                ('DeletedAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('EcosystemId', models.AutoField(primary_key=True, serialize=False)),
                ('EntityId', models.IntegerField(help_text='FK to entities.Entities')),
                ('EcosystemName', models.CharField(max_length=200)),
                ('EcosystemType', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('AreaHectares', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'ecosystem',
            },
        ),
        migrations.CreateModel(
            name='EcosystemTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EcosystemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecosystem_tags', to='ecosystem.ecosystem')),
                ('TagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecosystem_links', to='shared.tags')),
            ],
            options={
                'db_table': 'ecosystem_tags',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('Status', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted')),
                ('ApprovalStatus', models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending')),
                ('DeletedAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('SpeciesId', models.AutoField(primary_key=True, serialize=False)),
                ('EntityId', models.IntegerField(help_text='FK to entities.Entities')),
                ('CommonName', models.CharField(max_length=200)),
                ('ScientificName', models.CharField(blank=True, max_length=200, null=True)),
                ('Family', models.CharField(blank=True, max_length=100, null=True)),
                ('Kingdom', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('IUCNStatus', models.CharField(blank=True, choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], max_length=2, null=True)),
                ('IUCNSyncedAt', models.DateTimeField(blank=True, null=True)),
                ('GBIFKey', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'species',
                'indexes': [models.Index(fields=['GBIFKey'], name='idx_species_gbif_key')],
            },
        ),
        migrations.CreateModel(
            name='SpeciesLandParcels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LandParcelId', models.IntegerField(help_text='FK to land.LandParcels (IntegerField — circular dep)')),
                ('SpeciesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_parcel_links', to='ecosystem.species')),
            ],
            options={
                'db_table': 'species_land_parcels',
            },
        ),
        migrations.CreateModel(
            name='SpeciesTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SpeciesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_tags', to='ecosystem.species')),
                ('TagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_links', to='shared.tags')),
            ],
            options={
                'db_table': 'species_tags',
            },
        ),
    ]
