# Generated by Django 5.1.4 on 2026-06-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecosystem',
            options={'ordering': ['EcosystemName']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['CommonName']},
        ),
    ]
