# Generated by Django 5.1.4 on 2026-08-21 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0003_species_biomass_params'),
        ('entities', '0005_entitymembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecosystem',
            name='EntityId',
            field=models.ForeignKey(db_column='EntityId', on_delete=django.db.models.deletion.PROTECT, related_name='ecosystems', to='entities.entities'),
        ),
        migrations.AlterField(
            model_name='species',
            name='EntityId',
            field=models.ForeignKey(db_column='EntityId', on_delete=django.db.models.deletion.PROTECT, related_name='species_records', to='entities.entities'),
        ),
    ]
