# Generated by Django 5.1.4 on 2026-08-31 05:35

from django.db import migrations, models

# Columns that are about to become NOT NULL. Existing NULLs must become '' first,
# otherwise the AlterField operations below fail on any populated database.
NULLABLE_TEXT_COLUMNS = {
    "ecosystem": ["Description", "EcosystemType"],
    "species": ["BiomassDataSource", "Description", "Family", "IPCCForestType", "IUCNStatus", "Kingdom", "ScientificName"],
}


def backfill_empty_strings(apps, schema_editor):
    for model_name, field_names in NULLABLE_TEXT_COLUMNS.items():
        model = apps.get_model("ecosystem", model_name)
        for field_name in field_names:
            model._default_manager.filter(**{field_name + "__isnull": True}).update(
                **{field_name: ""}
            )

    # The UPDATEs above queue deferred FK trigger events, and PostgreSQL refuses to
    # ALTER a table that has any pending -- "cannot ALTER TABLE because it has
    # pending trigger events". Both run in one transaction, so the AlterField
    # operations below would fail on any database that actually has rows. An empty
    # database updates nothing, queues nothing, and passes, which is why CI and a
    # fresh test database never caught this.
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def noop(apps, schema_editor):
    """Reverse is a no-op — '' and NULL are indistinguishable once merged."""


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0004_alter_ecosystem_entityid_alter_species_entityid'),
    ]

    operations = [
        migrations.RunPython(backfill_empty_strings, noop),
        migrations.AlterField(
            model_name='ecosystem',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ecosystem',
            name='EcosystemType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='BiomassDataSource',
            field=models.CharField(blank=True, help_text='Citation for biomass parameter values (IPCC table ref, study DOI)', max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='Family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='IPCCForestType',
            field=models.CharField(blank=True, choices=[('tropical', 'Tropical'), ('temperate', 'Temperate'), ('boreal', 'Boreal'), ('mangrove', 'Mangrove'), ('savanna', 'Savanna / Woodland'), ('shrubland', 'Shrubland'), ('grassland', 'Grassland')], help_text='IPCC forest type for Tier 1 BEF/R lookup', max_length=20),
        ),
        migrations.AlterField(
            model_name='species',
            name='IUCNStatus',
            field=models.CharField(blank=True, choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], max_length=2),
        ),
        migrations.AlterField(
            model_name='species',
            name='Kingdom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='species',
            name='ScientificName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
