# Generated by Django 5.1.4 on 2026-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissionfactors',
            options={'ordering': ['ActivityName']},
        ),
        migrations.AlterModelOptions(
            name='emissionfactorsets',
            options={'ordering': ['-ApplicableYear', 'SetName']},
        ),
        migrations.AlterModelOptions(
            name='emissionsdata',
            options={'ordering': ['-CreatedAt']},
        ),
        migrations.AlterModelOptions(
            name='ghginventories',
            options={'ordering': ['-ReportingYear']},
        ),
        migrations.AlterModelOptions(
            name='gwpdatasets',
            options={'ordering': ['-PublishedYear']},
        ),
        migrations.AlterModelOptions(
            name='targetmilestones',
            options={'ordering': ['MilestoneYear']},
        ),
        migrations.AlterModelOptions(
            name='targets',
            options={'ordering': ['-TargetYear']},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'ordering': ['UnitName']},
        ),
        migrations.AlterField(
            model_name='ghginventories',
            name='VerificationStatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unverified'), (2, 'Pending'), (3, 'Verified - First Party'), (4, 'Verified - Third Party'), (5, 'Submitted to CDP')], default=1),
        ),
    ]
