# Generated by Django 5.1.4 on 2026-08-31 05:35

from django.db import migrations, models

# Columns that are about to become NOT NULL. Existing NULLs must become '' first,
# otherwise the AlterField operations below fail on any populated database.
#
# Note on gwpvalues.GasSubtype: it takes part in the unique constraint
# unique_gwp_gas_per_dataset (GwpDatasetId, Gas, GasSubtype). Postgres treats
# NULLs as distinct, so duplicate (dataset, gas, NULL) rows were possible until
# now; collapsing NULL to '' makes that constraint bite for the first time. If
# this migration fails here with a uniqueness error, the database genuinely has
# duplicate GWP rows that must be de-duplicated before it can proceed.
NULLABLE_TEXT_COLUMNS = {
    "emissionfactors": ["ActivityCategory", "ClimatiqActivityId", "CountryCode", "GasSubtype", "GridSubregion"],
    "emissionfactorsets": ["GeographicScope", "Version"],
    "emissionsdata": ["ActivityDescription", "GasSubtype", "GridSubregion", "SpendCurrency", "SupplierName", "VerificationNotes"],
    "emissionsdetails": ["GasSubtype", "Remarks"],
    "emissionsoffsets": ["CertificateNumber", "CreditRegistry", "CreditSerialNumber", "RegistryProjectName", "RegistryProjectType", "RegistryRetirementBeneficiary", "RegistryValidationStatus", "Remarks"],
    "ghginventories": ["BoundaryNotes", "VerificationNotes"],
    "gwpvalues": ["GasSubtype"],
    "scope3relevanceassessments": ["ExclusionReason", "Notes"],
    "targetmilestones": ["Notes"],
    "targets": ["Notes"],
}


def backfill_empty_strings(apps, schema_editor):
    for model_name, field_names in NULLABLE_TEXT_COLUMNS.items():
        model = apps.get_model("emissions", model_name)
        for field_name in field_names:
            model._default_manager.filter(**{field_name + "__isnull": True}).update(
                **{field_name: ""}
            )


def noop(apps, schema_editor):
    """Reverse is a no-op — '' and NULL are indistinguishable once merged."""


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0009_emissionsdata_supplier_name'),
    ]

    operations = [
        migrations.RunPython(backfill_empty_strings, noop),
        migrations.AlterField(
            model_name='emissionfactors',
            name='ActivityCategory',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emissionfactors',
            name='ClimatiqActivityId',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emissionfactors',
            name='CountryCode',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='emissionfactors',
            name='GasSubtype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionfactors',
            name='GridSubregion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionfactorsets',
            name='GeographicScope',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emissionfactorsets',
            name='Version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionsdata',
            name='ActivityDescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emissionsdata',
            name='GasSubtype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionsdata',
            name='GridSubregion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionsdata',
            name='SpendCurrency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='emissionsdata',
            name='SupplierName',
            field=models.CharField(blank=True, help_text='Supplier shown on the bill, contract, or source evidence.', max_length=200),
        ),
        migrations.AlterField(
            model_name='emissionsdata',
            name='VerificationNotes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emissionsdetails',
            name='GasSubtype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emissionsdetails',
            name='Remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emissionsoffsets',
            name='CertificateNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emissionsoffsets',
            name='CreditRegistry',
            field=models.CharField(blank=True, choices=[('verra', 'Verra (VCS)'), ('gold_standard', 'Gold Standard'), ('other', 'Other / Unlisted')], help_text='Which registry validates this credit (drives the registry-sync task).', max_length=20),
        ),
        migrations.AlterField(
            model_name='emissionsoffsets',
            name='CreditSerialNumber',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emissionsoffsets',
            name='RegistryProjectName',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='emissionsoffsets',
            name='RegistryProjectType',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emissionsoffsets',
            name='RegistryRetirementBeneficiary',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='emissionsoffsets',
            name='RegistryValidationStatus',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('unverified', 'Unverified')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='emissionsoffsets',
            name='Remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ghginventories',
            name='BoundaryNotes',
            field=models.TextField(blank=True, help_text='Included/excluded operations and rationale for the inventory boundary.'),
        ),
        migrations.AlterField(
            model_name='ghginventories',
            name='VerificationNotes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gwpvalues',
            name='GasSubtype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scope3relevanceassessments',
            name='ExclusionReason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scope3relevanceassessments',
            name='Notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='targetmilestones',
            name='Notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='targets',
            name='Notes',
            field=models.TextField(blank=True),
        ),
    ]
