# Generated by Django 5.1.4 on 2026-06-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entities',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='EntityId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entities',
            name='FiscalYearEndMonth',
            field=models.PositiveSmallIntegerField(default=3, help_text="Month number (1–12) when the entity's fiscal year ends"),
        ),
        migrations.AlterField(
            model_name='entities',
            name='ParentEntityId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='entities.entities'),
        ),
        migrations.AlterField(
            model_name='entities',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='entityapikeysintermediary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entitycontacts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entitydocuments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entitylocations',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entitytags',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relatedentities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
