# Generated by Django 5.1.4 on 2026-06-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_entities_approvalstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entities',
            options={'ordering': ['EntityName']},
        ),
    ]
