# Generated by Django 5.1.4 on 2026-08-31 05:35

from django.db import migrations, models

# Columns that are about to become NOT NULL. Existing NULLs must become '' first,
# otherwise the AlterField operations below fail on any populated database.
NULLABLE_TEXT_COLUMNS = {
    "entities": ["AddressLine1", "AddressLine2", "City", "CompaniesHouseNumber", "Country", "ExternalRegistryUrl", "PostCode", "RegistrationNumber", "VATNumber"],
    "relatedentities": ["RelationshipType"],
}


def backfill_empty_strings(apps, schema_editor):
    for model_name, field_names in NULLABLE_TEXT_COLUMNS.items():
        model = apps.get_model("entities", model_name)
        for field_name in field_names:
            model._default_manager.filter(**{field_name + "__isnull": True}).update(
                **{field_name: ""}
            )

    # The UPDATEs above queue deferred FK trigger events, and PostgreSQL refuses to
    # ALTER a table that has any pending -- "cannot ALTER TABLE because it has
    # pending trigger events". Both run in one transaction, so the AlterField
    # operations below would fail on any database that actually has rows. An empty
    # database updates nothing, queues nothing, and passes, which is why CI and a
    # fresh test database never caught this.
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


def noop(apps, schema_editor):
    """Reverse is a no-op — '' and NULL are indistinguishable once merged."""


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_entitymembers'),
    ]

    operations = [
        migrations.RunPython(backfill_empty_strings, noop),
        migrations.AlterField(
            model_name='entities',
            name='AddressLine1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entities',
            name='AddressLine2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entities',
            name='City',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entities',
            name='CompaniesHouseNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entities',
            name='Country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entities',
            name='ExternalRegistryUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entities',
            name='PostCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entities',
            name='RegistrationNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entities',
            name='VATNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='relatedentities',
            name='RelationshipType',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
