# Generated by Django 5.1.4 on 2026-06-22 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_alter_entities_approvalstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJobs',
            fields=[
                ('ReportJobId', models.AutoField(primary_key=True, serialize=False)),
                ('ReportType', models.CharField(choices=[('emissions_summary', 'Project Emissions Summary'), ('ghg_inventory', 'Entity GHG Inventory'), ('phase_progress', 'Phase Progress vs Goals'), ('tree_log', 'Tree Removal & Restoration Log')], max_length=50)),
                ('Format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('Parameters', models.JSONField(default=dict)),
                ('JobStatus', models.PositiveSmallIntegerField(choices=[(1, 'Queued'), (2, 'Processing'), (3, 'Complete'), (4, 'Failed')], default=1)),
                ('CeleryTaskId', models.CharField(blank=True, max_length=255, null=True)),
                ('S3Key', models.TextField(blank=True, null=True)),
                ('FileSizeBytes', models.BigIntegerField(blank=True, null=True)),
                ('ErrorMessage', models.TextField(blank=True, null=True)),
                ('QueuedAt', models.DateTimeField(auto_now_add=True)),
                ('StartedAt', models.DateTimeField(blank=True, null=True)),
                ('CompletedAt', models.DateTimeField(blank=True, null=True)),
                ('PurgeAfter', models.DateTimeField()),
                ('EntityId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_jobs', to='entities.entities')),
                ('RequestedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_jobs',
                'ordering': ['-QueuedAt'],
                'indexes': [models.Index(fields=['EntityId', 'JobStatus'], name='idx_report_entity_status'), models.Index(fields=['PurgeAfter'], name='idx_report_purge')],
            },
        ),
    ]
