# Generated by Django 5.1.4 on 2026-06-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='LogId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='RetentionTier',
            field=models.PositiveSmallIntegerField(default=2, help_text='1: 30-day, 2: 1-year (login/session), 3: 7-year (CRUD/regulatory)'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='ContactId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='EntityId',
            field=models.IntegerField(help_text='FK to entities.Entities (IntegerField — avoids circular import)'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='DocumentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='documenttags',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entityapikeys',
            name='ApiKeyId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entityapikeys',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='entityapikeys',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='images',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='images',
            name='ImageId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='images',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='imagetags',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locations',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='GPSCoordinates',
            field=models.JSONField(default=dict, help_text="GeoJSON Point: { type: 'Point', coordinates: [lng, lat] }"),
        ),
        migrations.AlterField(
            model_name='locations',
            name='LocationId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locations',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ApprovalStatus',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Rejected, 3: Pending'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='EntityId',
            field=models.IntegerField(help_text='FK to entities.Entities (IntegerField — avoids circular import)'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='Status',
            field=models.PositiveSmallIntegerField(default=1, help_text='1: Active, 2: Disabled, 3: Draft, 4: Deleted'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='TagId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
