# Generated by Django 5.1.4 on 2026-08-31 05:35

from django.db import migrations, models

# Columns that are about to become NOT NULL. Existing NULLs must become '' first,
# otherwise the AlterField operations below fail on any populated database.
NULLABLE_TEXT_COLUMNS = {
    "auditlog": ["ChangedByUsername", "Description", "IpAddress", "TableName", "UserAgent"],
    "contacts": ["AddressLine1", "AddressLine2", "AddressTitle", "Country", "Designation", "Email", "PhoneNumber", "PostCode"],
    "documents": ["Description", "DocField", "Excerpt"],
    "images": ["AltText", "CopyrightInfo", "Description"],
    "locations": ["Remarks"],
}


def backfill_empty_strings(apps, schema_editor):
    for model_name, field_names in NULLABLE_TEXT_COLUMNS.items():
        model = apps.get_model("shared", model_name)
        for field_name in field_names:
            model._default_manager.filter(**{field_name + "__isnull": True}).update(
                **{field_name: ""}
            )


def noop(apps, schema_editor):
    """Reverse is a no-op — '' and NULL are indistinguishable once merged."""


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_alter_auditlog_logid_alter_auditlog_retentiontier_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_empty_strings, noop),
        migrations.AlterField(
            model_name='auditlog',
            name='ChangedByUsername',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='IpAddress',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='TableName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='UserAgent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='AddressLine1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='AddressLine2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='AddressTitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='Email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='PostCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='documents',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='DocField',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='documents',
            name='Excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='AltText',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='images',
            name='CopyrightInfo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='Remarks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
